### PR TITLE
Husky - post-merge

### PR DESCRIPTION
**Pull request by bh2smith**
This package was insisting to install itself, so I thought I would give it a try. As far as I can tell it creates its own `post-commit` hook.

```
#!/bin/sh
# husky

# Hook created by Husky
#   Version: 2.5.0
#   At: 25/06/2019, 10:24:22
#   See: https://github.com/typicode/husky#readme

# From
#   Directory: /Users/admin/Projects/gnosis/dex-contracts/node_modules/husky
#   Homepage: https://github.com/typicode/husky#readme

scriptPath="node_modules/husky/run.js"
hookName=`basename "$0"`
gitParams="$*"

debug() {
  if [ "${HUSKY_DEBUG}" = "true" ] || [ "${HUSKY_DEBUG}" = "1" ]; then
    echo "husky:debug $1"
  fi
}

debug "$hookName hook started"

if [ "${HUSKY_SKIP_HOOKS}" = "true" ] || [ "${HUSKY_SKIP_HOOKS}" = "1" ]; then
  debug "HUSKY_SKIP_HOOKS is set to ${HUSKY_SKIP_HOOKS}, skipping hook"
  exit 0
fi


if ! command -v node >/dev/null 2>&1; then
  echo "Info: can't find node in PATH, trying to find a node binary on your system"
fi

if [ -f "$scriptPath" ]; then
  # if [ -t 1 ]; then
  #   exec < /dev/tty
  # fi
  if [ -f ~/.huskyrc ]; then
    debug "source ~/.huskyrc"
    . ~/.huskyrc
  fi
  node_modules/run-node/run-node "$scriptPath" $hookName "$gitParams"
else
  echo "Can't find Husky, skipping $hookName hook"
  echo "You can reinstall it using 'npm install husky --save-dev' or delete this hook"
fi
```

Not sure what is supposed to be.

### CODE REVIEW

**Comment by bh2smith** [comment]
Realistically, I would like to know exactly why this husky package has been interfering with this project without my consent. Observe the following situation, 

- checkout new branch to work on some task
- be warned that husky is not working properly

```
➜  dex-contracts git:(master) ✗ git checkout -b conditional_coverage
M       package-lock.json
Switched to a new branch 'conditional_coverage'
Can't find Husky, skipping post-checkout hook
You can reinstall it using 'npm install husky --save-dev' or delete this hook
```

what is this?

**Comment by fleupold** [comment]
From https://github.com/typicode/husky#readme

> Husky can prevent bad git commit, git push and more 🐶 woof!

Looks cool. It's basically an easy way to describe which commands should run pre-commit, pre-push. I'm fine with adding this.

**Review by fleupold — APPROVED** [review]
🐶

**Comment by bh2smith** [comment]
Notice @fleupold that this has automatically disabled `pre-commit` added because we already have our own. Meaning it ignored creating its own pre-commit. I guess for future devs they will have at least something

**Review by josojo — APPROVED** [review]
I don't have any experience with husky. But I am okay with giving it a try

**Comment by bh2smith** [comment]
Let's try it out!

**Pull request merged**
