### PR TITLE
[Easy] Package Update

### PR DESCRIPTION
**Pull request by bh2smith**
These changes are merely a result of result of 

```bash
npm install
npm audit fix
```

which also happens to be the test plan... followed by running the unit tests

### CODE REVIEW

**Comment by josojo** [comment]
What am I doing wrong?
`➜  dex-contracts git:(2714adc) ✗ npm audit fix
up to date in 1.151s
fixed 0 of 2 vulnerabilities in 1344 scanned packages
  2 vulnerabilities required manual review and could not be updated`

**Comment by bh2smith** [comment]
@josojo this is totally normal, there are some vulnerabilities with web3 that haven't been patched yet.

**Review by fleupold — APPROVED** [review]
🆙

**Review by josojo — APPROVED** [review]
thanks!

**Pull request merged**
