### PR TITLE
Refactor state index #203

### PR DESCRIPTION
**Pull request by josojo**
deals with issue #203

renames state index to batchId, as discussed in slack and requested by anxo.

---
Testplan: Unit tests.

### CODE REVIEW

**Review by anxolin — APPROVED** [review]
Easier to read and more gas efficient, two for the price of one!

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia0.giphy.com%2Fmedia%2F8dYmJ6Buo3lYY%2Fgiphy.gif&token=read" data-gitmeme-token="read"></a>

**Review by fleupold — APPROVED** [review]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2FzcCGBRQshGdt6%2Fgiphy.gif&token=easy" data-gitmeme-token="easy"></a>

**Review by bh2smith — COMMENTED** [review]
Sweet deal!

**Comment by fleupold** [comment]
This is a wonderful example of a PR that creates a breaking change for the dex-services repo. I'd argue that in order to call this PR "done" it would involve updating the dependent call-sites as well.

However, since we have separate repos with separate CIs it's very easy to forget that and then when someone wants to merge their changes they have to fix a bunch of unrelated breakages as well.

**Comment by josojo** [comment]
Sorry, @fleupold 

definitively see your point. I am happy to join the repos.

**Pull request merged**
