### PR TITLE
New npm version

### LINKED ISSUE #549: [Easy] Publish new npm package.
Explicitly want to include #544

### PR DESCRIPTION
**Pull request by bh2smith**
Closes #549.

### CODE REVIEW

**Review by fleupold — APPROVED** [review]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2Ftoe6vBrtWgKvKW7Ehz%2Fgiphy.gif&token=bump" data-gitmeme-token="bump"></a>

**Comment by josojo** [comment]
@bh2smith Is this one still needed?

**Comment by bh2smith** [comment]
@josojo I was told that everything would happen automatically when this was merged.... It is still required by `dex-liquidity-provision` that we update the npm module. It doesn't matter if it is this version or the next.

It has been so long now, that it probably makes more sense to simply include more stuff in the next publish.

**Comment by nlordell** [comment]
@bh2smith Once this PR is merged, you can create a new tag [here](https://github.com/gnosis/dex-contracts/releases/new) with a "Tag version" of `v0.2.3` (note that it MUST match the version in the `package.json` as a security precaution) and then it will just happen like :stars: magic :stars:.

**Pull request merged**
