### PR TITLE
Function signature:internal->private, public->external

### PR DESCRIPTION
**Pull request by josojo**
As discussed with anxo, I checked all the function signatures.

We used internal as a function signature a lot, although it would only be required for inheritance.

I would love to make submitSolution as external, but then I am running into stack-too-deep errors, as then the arrays: prices, tokenIdsForPrice are declared as calldata and memory, and hence use more space in the stack

---
testplan: test suite only

### CODE REVIEW

**Review by fleupold — COMMENTED** [review]
Is this really saving anything? If all arrays stay memory on e.g. `cancelOrders` and `placeValidFromOrders` I'd expect the same number of memcopies to happen so I'm not sure this is achieving anything. Can we run a quick gas check?

**Comment by josojo** [comment]
Isn't it just cleaner and better practice to define external functions as external and not public? It improves readability it general.

**Comment by josojo** [comment]
Would you agree that having private functions over internal ones is better, if we don't work with inheritance?

Anyways, let me quickly do the gas check, but I also doubt that it would be more gas efficient.

**Comment by fleupold** [comment]
> Isn't it just cleaner and better practice to define external functions as external and not public?

I don't think it adds much value, if the only function we can declare external is `replaceOrders`.

**Comment by josojo** [comment]
The gas cost difference is that the replaceOrders unit test:
    it.only("cancels and creates new orders", async () => {
 cost 100 more gas, if we have it external, instead of private

**Review by fleupold — APPROVED** [review]

**Pull request merged**
