### PR TITLE
removing IsSellOrderFlag

### PR DESCRIPTION
**Pull request by josojo**
Clean up: removing the old isSellOrderFlag

I guess after the meeting today, it became clear that we will never implement the other logic for buyOrders. Hence I am removing it completely

solves issue #202

testplan:
Unit test

Attention:
Do not merge, as it effects driver as well

### CODE REVIEW

**Review by fleupold — APPROVED** [review]
Looks good. Does this need updates in the services repo? E.g. does the placeOrder script need to be adjusted and does the way rust parse orders still work?

**Review by bh2smith — APPROVED** [review]
This is cool and I approve of the change, but I am worried that there will be hundreds of lines of conflicts with other recent changes (particularly in the test files involving submit solution). In any case, I am not afraid of a few hundred lines of conflicts, just mentioning...

**Comment by josojo** [comment]
Thanks for your reviews guys.

Anyways, I will split this PR into two. The last 3 commits are not related to the title

**Comment by bh2smith** [comment]
> putting multicall into dependencies in package.json

I am not sure I approve of this. multicall is a DevDependency, why does it need to be moved?

**Comment by josojo** [comment]
@bh2smith, please take a look here:
https://github.com/gnosis/dex-contracts/pull/247

**Comment by fleupold** [comment]
> multicall is a DevDependency, why does it need to be moved?

In that case we need to change the travis script `setup-contracts.sh` to not use `npm install --production`. Either way, this is not related to this PR so maybe we can have this reverted here and focus on the removal of the flag?

Let's only merge this once the PR for dex-services is ready too.

**Comment by bh2smith** [comment]
Finally someone included a link to this mysterious other issue that everyone been talking about!

https://github.com/gnosis/dex-services/pull/275

**Pull request merged**
