### PR TITLE
Revert "Increase MAX_TOUCHED_ORDERS to 30"

### PR DESCRIPTION
**Pull request by bh2smith**
Reverts gnosis/dex-contracts#476

### CODE REVIEW

**Comment by nlordell** [comment]
Just curious, why?

**Review by nlordell — APPROVED** [review]

**Comment by bh2smith** [comment]
@nlordell - its all here: https://github.com/gnosis/dex-contracts/pull/476

**Review by josojo — APPROVED** [review]
Since your PR was not breaking anything, an "only-fix PR" would have been sufficient. But as you prefer...

**Comment by bh2smith** [comment]
I’m thinking maybe it’s better not to revert and just fix the problem. Since it doesn’t affect the build anyway. @josojo?

**Comment by fleupold** [comment]
Agreed. We can forward fix instead of reverting.

**Comment by nlordell** [comment]
Failure:
```
1) ensures hard gas limit on largest possible ring trade 
```
:boom:

**Comment by bh2smith** [comment]
I don't understand @nlordell's last comment, but closing this in favour of a fix

**Comment by nlordell** [comment]
@bh2smith Sorry! That was meant for #482 where the build was failing. I have too many tabs open.

**Pull request closed without merging**
