### PR TITLE
[Easy] Move special migration scripts out of subdirectories

### PR DESCRIPTION
**Pull request by bh2smith**
No major change, just noticed that migration scripts were sitting all alone in their own directories.

### CODE REVIEW

**Comment by fleupold** [comment]
no concerns from my side.

@josojo can you explain again why we need those scripts in a src directory rather than using that in the migrations directly? I always struggle navigating to the migration code that really matters because of this indirection.

**Comment by bh2smith** [comment]
> why we need those scripts in a src directory

My only guess might be that every script in the migrations directory are considered migration scripts by truffle... I would be really happy if they were all in one place though if this is possible.

**Comment by fleupold** [comment]
If I remember correctly it was done like this in the dutchX because the scripts could have been run from different truffle projects or something like this. However, I'd really like to re-evaluate if this applies to our project as well (cc @anxolin).

Right now it adds more friction than benefit to me.

**Review by josojo — APPROVED** [review]
Thanks!

**Comment by josojo** [comment]
> If I remember correctly it was done like this in the dutchX because the scripts could have been run from different truffle projects or something like this. However, I'd really like to re-evaluate if this applies to our project as well (cc @anxolin).

Yes, exactly this was the reason. I am not aware of any solution, which would just reuse the migration scripts in other projects.

To be honest, I don't see the friction that it is creating. 

When I did it, I had in mind to do it cleanly right from the beginning and allow any other protocol to theoretically integrate this project into theirs.

**Comment by anxolin** [comment]
By the time I made the migrations, there was no easy way to migrate other projects you depend on. 
After talking to everyone I could, we couldn't find a solution.

Happy that my solution is reevaluated, there might be sth now. Anyways, it uses a simple principle. Truffle scripts inject global vars (bad practice), so your scripts become dependent on some "magic". My solution is declare it as pure functions with all the dependencies injected so any project can execute the code providing their instance of these "magic globals"

**Comment by fleupold** [comment]
The friction that it is creating is another hop in our code logic whenever you try to look at it or change it (especially in github or vim, where you cannot easily click-follow the link). 
I see the stylistic upside of having pure functions without global state, but couldn't those live in the same file?

**Comment by bh2smith** [comment]
Shall I assume this issue will remain open until we are all satisfied with the location and usage of migration scripts?

Realistically, from my perspective, the content of whatever is in `src/special_stablex_script.js` could easily just live directly in `migrations/3_stablex.js`. Do we really save anything by leaving `migrations/3_stablex.js` completely hollow?

**Comment by josojo** [comment]
I don't mind which solution we are picking, as long as the contracts can be migrated from outside

**Comment by fleupold** [comment]
> I don't mind which solution we are picking, as long as it can be migrated from outside

The only argument that is added in the separately exported version is artifacts. This value is only globally exposed in truffle, so if you use some other framework to do the migration you would have to expose it globally instead of passing it as an argument (either way it has to be created somehow)

I'd like to see a use case that uses this separate file approach which couldn't just `require("migrations/x_migrateY.js")` directly.

Generally, I'd err on the side of having it as simple as possible until somebody actually wants to deploy it in a complicated one-off fashion.

**Comment by bh2smith** [comment]
Whats the deal with this? Is it still a thing? Cuz I think its a good start. @josojo and @fleupold?

**Pull request merged**
