### PR TITLE
Using OWL instead of GNO for the fee Token

### PR DESCRIPTION
**Pull request by josojo**
as title

---

Testplan: use the new migration script

```
export PK= ... // PK with your Rinkbey ETH
npx truffle migrate --reset --network rinkeby 
```

### CODE REVIEW

**Review by bh2smith — APPROVED** [review]
Hot 🌶

**Comment by josojo** [comment]
For me, the rinkeby migration stalls all the time.

```
1_initial_migration.js
======================

   Replacing 'Migrations'
   ----------------------
   > transaction hash:    0x11fc6d6a379c78e95d706f6f0b17c4c4fb5a4f1927ba49535c1cc36a49136d27
   ⠴ Blocks: 5            Seconds: 84
```

The same thing is happening on master branch, even on the historic commit, where I did the first migration in the past.

When I was pushing this PR last Friday, I thought it would be something temporarily with the Rinkeby network. But today, I have the same issue! Weird. I will investigate further.

@bh2smith Did you do the migration on Friday?

**Comment by bh2smith** [comment]
> @bh2smith Did you do the migration on Friday?

Certainly not that I am aware of. I am also not sure what is the problem here...

**Comment by bh2smith** [comment]
This worked fine for me with one additional instruction (note the space in the second instruction).

```bash
npm install
 export PK=[myRinkebyPK]
npx truffle migrate --reset --network rinkeby
```

Here is the output


```bash
➜  dex-contracts git:(usingOWL) ✗ npx truffle migrate --reset --network rinkeby

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.


Migrations dry-run (simulation)
===============================
> Network name:    'rinkeby-fork'
> Network id:      4
> Block gas limit: 0x6bf14b


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
   > block number:        5341467
   > block timestamp:     1572261106
   > account:             0x7461D0E562e54c591d5cc56c32ef280a3130CeD6
   > balance:             18.744845725
   > gas used:            206171
   > gas price:           25 gwei
   > value sent:          0 ETH
   > total cost:          0.005154275 ETH

   -------------------------------------
   > Total cost:         0.005154275 ETH


2_dev_dependencies.js
=====================
Not in development, so nothing to do. Current network is rinkeby-fork
   -------------------------------------
   > Total cost:                   0 ETH


3_batch_auction.js
==================

   Linking
   -------
   * Contract: SnappBaseCore <--> Library: IdToAddressBiMap 

   Deploying 'SnappBaseCore'
   -------------------------
   > block number:        5341470
   > block timestamp:     1572261111
   > account:             0x7461D0E562e54c591d5cc56c32ef280a3130CeD6
   > balance:             18.687237425
   > gas used:            2250474
   > gas price:           25 gwei
   > value sent:          0 ETH
   > total cost:          0.05626185 ETH


   Linking
   -------
   * Contract: SnappAuction <--> Library: IdToAddressBiMap 

   Linking
   -------
   * Contract: SnappAuction <--> Library: SnappBaseCore 

   Deploying 'SnappAuction'
   ------------------------
   > block number:        5341471
   > block timestamp:     1572261119
   > account:             0x7461D0E562e54c591d5cc56c32ef280a3130CeD6
   > balance:             18.59669015
   > gas used:            3621891
   > gas price:           25 gwei
   > value sent:          0 ETH
   > total cost:          0.090547275 ETH

   -------------------------------------
   > Total cost:         0.146809125 ETH


4_stablecoin_converter.js
=========================

   Linking
   -------
   * Contract: StablecoinConverter <--> Library: IdToAddressBiMap 

   Linking
   -------
   * Contract: StablecoinConverter <--> Library: IterableAppendOnlySet 
Deploy StablecoinConverter contract

   Deploying 'StablecoinConverter'
   -------------------------------
   > block number:        5341473
   > block timestamp:     1572261132
   > account:             0x7461D0E562e54c591d5cc56c32ef280a3130CeD6
   > balance:             18.500596625
   > gas used:            3816812
   > gas price:           25 gwei
   > value sent:          0 ETH
   > total cost:          0.0954203 ETH

   -------------------------------------
   > Total cost:           0.0954203 ETH


Summary
=======
> Total deployments:   4
> Final cost:          0.2473837 ETH


Starting migrations...
======================
> Network name:    'rinkeby'
> Network id:      4
> Block gas limit: 0x6bec62


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
   > transaction hash:    0x0945da49e5f293e9710cf03f87529346c5ed6a781137f26169d8e4b630d2cb4f
   > Blocks: 1            Seconds: 20
   > contract address:    0xb4340Fa3A216034B578755112EEA48CbF5f15b42
   > block number:        5341470
   > block timestamp:     1572261172
   > account:             0x7461D0E562e54c591d5cc56c32ef280a3130CeD6
   > balance:             18.744470725
   > gas used:            221171
   > gas price:           25 gwei
   > value sent:          0 ETH
   > total cost:          0.005529275 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:         0.005529275 ETH


2_dev_dependencies.js
=====================
Not in development, so nothing to do. Current network is rinkeby

   > Saving migration to chain.
   -------------------------------------
   > Total cost:                   0 ETH


3_batch_auction.js
==================

   Linking
   -------
   * Contract: SnappBaseCore <--> Library: IdToAddressBiMap (at address: 0x31172bB2B5f97E8E89cf3376495d7Bc7252f5a53)

   Deploying 'SnappBaseCore'
   -------------------------
   > transaction hash:    0x85edee061528e7eca724324deb5664efb4cfdc9930ac50f92ec43804a98d648f
   > Blocks: 0            Seconds: 8
   > contract address:    0x9Da1b2B0EFf4d62B95644A92356C65b467fADfab
   > block number:        5341473
   > block timestamp:     1572261217
   > account:             0x7461D0E562e54c591d5cc56c32ef280a3130CeD6
   > balance:             18.686487425
   > gas used:            2250474
   > gas price:           25 gwei
   > value sent:          0 ETH
   > total cost:          0.05626185 ETH


   Linking
   -------
   * Contract: SnappAuction <--> Library: IdToAddressBiMap (at address: 0x31172bB2B5f97E8E89cf3376495d7Bc7252f5a53)

   Linking
   -------
   * Contract: SnappAuction <--> Library: SnappBaseCore (at address: 0x9Da1b2B0EFf4d62B95644A92356C65b467fADfab)

   Deploying 'SnappAuction'
   ------------------------
   > transaction hash:    0x2b2aee0a6d4c5c50e6064414ee89311fb46776f24eb1454ebf8cda3f375eca04
   > Blocks: 0            Seconds: 12
   > contract address:    0xF8F601252ba025c52a2617eD4F9D8d73023ef447
   > block number:        5341474
   > block timestamp:     1572261232
   > account:             0x7461D0E562e54c591d5cc56c32ef280a3130CeD6
   > balance:             18.59369015
   > gas used:            3711891
   > gas price:           25 gwei
   > value sent:          0 ETH
   > total cost:          0.092797275 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:         0.149059125 ETH


4_stablecoin_converter.js
=========================

   Linking
   -------
   * Contract: StablecoinConverter <--> Library: IdToAddressBiMap (at address: 0x31172bB2B5f97E8E89cf3376495d7Bc7252f5a53)

   Linking
   -------
   * Contract: StablecoinConverter <--> Library: IterableAppendOnlySet (at address: 0x85ab87B703265D10Ac025687cB180f7187193F13)
Deploy StablecoinConverter contract

   Deploying 'StablecoinConverter'
   -------------------------------
   > transaction hash:    0x4b452ee24d0dfe957bd478a630bf64d016efbc30350369dd46438a2211456460
   > Blocks: 1            Seconds: 12
   > contract address:    0xC100a0dc36D759d945D5b4eD23d6c03636ad7965
   > block number:        5341476
   > block timestamp:     1572261262
   > account:             0x7461D0E562e54c591d5cc56c32ef280a3130CeD6
   > balance:             18.495721625
   > gas used:            3891812
   > gas price:           25 gwei
   > value sent:          0 ETH
   > total cost:          0.0972953 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:           0.0972953 ETH


Summary
=======
> Total deployments:   4
> Final cost:          0.2518837 ETH
```

**Comment by bh2smith** [comment]
It appears this migration  deploys both projects... I would have liked to know which flags I could have used to avoid deploying a bunch of unnecessary stuff.

**Comment by josojo** [comment]
@bh2smith Awesome. That helped a lot. 
I could figure out my problem. I had a transaction stuck in mem pool, hence my nonce was not correct and the transaction could not be minted. Now it all works smooth.

Yeah, in another PR, I can improve the deployment README.md. You are right.

**Pull request merged**
