### PR TITLE
(lint warnings) trailing whitespace.

### PR DESCRIPTION
**Pull request by bh2smith**
Not related to any existing issues. Just some warnings and errors that had been sitting in my local for some weeks here.

### CODE REVIEW

**Review by josojo — APPROVED** [review]
blinky clean

**Review by fleupold — APPROVED** [review]
Sparkling clean

 🛀 

Is there a way to make this part of our solhint process so that these things will not keep creeping in for people that work with another IDE?

**Comment by bh2smith** [comment]
@fleupold My solhint warns me of these errors. I will continue to enforce linting.

**Comment by fleupold** [comment]
> My solhint warns me of these errors. I will continue to enforce linting.

@bh2smith in this case can you add the rule that causes this to the `.solhint.json` or make it somehow else part of Travis CI? It's much better when we agree on a style and enforce this on every PR rather than relying on a hero making these clean-ups in regular intervals.

**Pull request merged**
