### PR TITLE
103 Solidity Coverage time increase fix

### LINKED ISSUE #103: [Bug] Coverage Fails on waitForNSeconds
Observe that this function

https://github.com/gnosis/dex-contracts/blob/300b69cf8b5006bd763da09c1bbe602a7100f43a/test/utilities.js#L118-L122

when changed to 

```js
const waitForNSeconds = async function(seconds, web3Provider=web3) {
  const currentBlock = await web3Provider.eth.getBlockNumber()
  const currentTime = (await web3Provider.eth.getBlock(currentBlock)).timestamp
  console.log("Current Time: ", currentTime)
  await send("evm_mine", [currentTime + seconds], web3Provider)
  const nextBlock = await web3Provider.eth.getBlockNumber()
  console.log("New Time: ", (await web3Provider.eth.getBlock(nextBlock)).timestamp)
}
```

outputs 
```
Current Time:  1559735013
New Time:  1559735013
```
when running `./node_modules/.bin/solidity-coverage`

but actually works when running `truffle test`

Subscribing @fleupold or @josojo. Any ideas?

### PR DESCRIPTION
**Pull request by bh2smith**
Closes #103.

Test Plan: Run coverage report and truffle test

`./node_modules/.bin/solidity-coverage`

### CODE REVIEW

**Review by fleupold — COMMENTED** [review]
Is removing the `isActive` function required? I think this makes debugging things a bit harder. What if we send an `evm_mine` after the `evm_increaseTime`? Shouldn't this update both the time and the current block?

**Comment by bh2smith** [comment]
@fleupold unfortunately the isActive function no longer works, this is why I have removed it. I have not been able to figure out what is wrong with it. I will try the evm_mine after the increased time... (for some reason when I tried before it was the other way around which makes absolutely no sense and probably is why it didn't work).

**Comment by bh2smith** [comment]
All fixed! Works like a charm!

Screenshot 2019-06-06 at 3 24 27 PM

**Review by josojo — APPROVED** [review]
Sometimes one line of code can change a lot! 
Great

**Review by fleupold — APPROVED** [review]
🆒

**Pull request merged**
