### PR TITLE
reuse checkOrderValidity in freeStorageOfOrder

### LINKED ISSUE #354: [Easy] Reuse `checkOrderValidity` in `freeStorageOfOrder`
As John W. correctly pointed out in telegram, here we should call `checkOrderValidity` to allow people to cancel and free storage of orders that are **not yet** valid (e.g. the ones that had just been placed).

https://github.com/gnosis/dex-contracts/blob/8f4e8518d27d0777b57f8d3c8154b1c769445698/contracts/BatchExchange.sol#L202

> I hope you don't mind me poking at this :) ... freeStorageOfOrders() seems to be unnecessarily strict by checking only vaild until and not looking at valid from. If I understand the convention then, getCurrentBatch()-1 is the batch index that is currently being solved. Then calling checkOrderValidity(getCurrentBatch()-1) could be used for checking whether the order can be safely deleted. That way it would be possible to delete orders for next batch that are not being solved yet. We could then replace orders for next batch (by combining cancel, free and place).

### PR DESCRIPTION
**Pull request by fleupold**
Closes #354 

### Test Plan

Added a unit test that was failing before.

### CODE REVIEW

**Comment by fleupold** [comment]
After thinking about it more and specifically with #362 in mind, it probably makes sense to remove `freeStorageOfOrder` altogether and just free the storage when we can inside the cancellation method.

This makes the contract interface more concise, and I doubt a lot of people will actually free their storage after the fact. For those, it should be fine to call cancelOrders again (the only added gas cost is the CancelOrder event emission).

**Review by josojo — APPROVED** [review]
Hm... it is a little bit strange that one has to call the same function twice to delete a valid order. 

Though I see your point that this allows us to do most of the work in one step. Compared to a solution with 2 functions, your solution saves 1 time the check checkOrderValidity and loading a bunch of variables. 

I am okay with your proposal. Thanks for thinking this through.

**Review by bh2smith — APPROVED** [review]
Looks great! From my understanding of the code, it seems we now use cancel order for both purposes (cancelation and deletion) rather than having two separate functions. It appears that an order is only deleted if it has already expired or if the function is called twice... 

I find it somewhat strange that `OrderCancelation` event is emitted twice..  Would it be a good idea to have different events `Cancellation` and `Deletion` emitted  inside the if statement?

**Comment by fleupold** [comment]
> Would it be a good idea to have different events Cancellation and Deletion emitted inside the if statement?

I figured that even in the current state nothing is preventing you from calling cancellation many times and thus I didn't think the event was so important. Do we really care to know if an order was just made invalid or freed from storage?

**Comment by bh2smith** [comment]
> Do we really care to know if an order was just made invalid or freed from storage?

In that case, do we really need any event at all? Seems less confusing.

**Comment by fleupold** [comment]
> In that case, do we really need any event at all?

I think having an event cannot hurt, it will allow easy analytics on how many "active" traders we have (ones that change their orders rather than letting them fade out).

**Pull request merged**
