### PR TITLE
[Cleanup] .eslintrc is deprecated.

### PR DESCRIPTION
**Pull request by nlordell**
I noticed we had multiple `.eslintrc` files in the root. After doing some digging in the [user guide](https://eslint.org/docs/user-guide/configuring) I found out that:

> Deprecated - use `.eslintrc`, which can be either JSON or YAML.

So I ported `{scipts,test}/.eslintrc` to `.eslintrc.js` format.

Additionally:
> If there are multiple configuration files in the same directory, ESLint will only use one. The priority order is:
> <span>1.</span> `.eslintrc.js`
> ...
> <span>6.</span> `.eslintrc`

This can be confirmed by running ESLint in debug mode, the output indicates that only the `.eslintrc.js` file was being read:
```
$ npx eslint . --debug 2>&1 | grep eslintrc
2020-04-30T07:09:58.031Z eslint:config-array-factory Loading JS config file: /var/home/nlordell/Developer/gnosis/dex-contracts/.eslintrc.js
...
```

So I removed the root `.eslintrc` which was being ignored anyway.

### Test Plan

CI still works and no linter errors are produced.

### CODE REVIEW

**Review by e00E — APPROVED** [review]

**Review by fleupold — APPROVED** [review]
Great cleanup! It would be awesome if we had a standard template for our repos that new repos can just bootstrap from.

**Review by bh2smith — APPROVED** [review]
This looks great but it also appears that we lost a lot of lint configuration... Like, for example, no semi colon and two space indentation. Are these now defaults?

**Comment by nlordell** [comment]
> Like, for example, no semi colon and two space indentation. Are these now defaults?

I guess so. The lint configuration that was removed was being ignored anyway.

**Comment by nlordell** [comment]
> It would be awesome if we had a standard template for our repos that new repos can just bootstrap from.

@anxolin Do you guys have a standard `.eslintrc.js` file we can shamelessly steal? We can add it in a follow up PR to keep our linting consistent.

**Comment by anxolin** [comment]
> @anxolin Do you guys have a standard .eslintrc.js file we can shamelessly steal? We can add it in a follow up PR to keep our linting consistent.

@nlordell 
We are happy with this one: https://github.com/gnosis/dex-js/blob/master/.eslintrc.js

**Comment by fleupold** [comment]
Random thought not related to this PR but given we have so many similar repo structures, maybe we want to create a gnosis template repo for js, smart contracts, python projects etc. (https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository)

**Comment by anxolin** [comment]
It's a good idea, I'd do it if we are bootstrapping many similar projects.
I think for now we are not there, I would do it if we start to make many webs, many libs, and even in that case, we should consider having core modules as a regular dependencies that shares this.

Also other use case for the templates might be for the dev portal, to bootstrap projects. Also interesting and worth exploring the truffle boxes and other template tools out there

**Comment by bh2smith** [comment]
> Random thought not related to this PR but given we have so many similar repo structures, maybe we want to create a gnosis template repo for JS, smart contracts, python projects etc.

We could also have a scaffolding command to initialize a project!

**Pull request merged**
